spring:
  h2:
    console:
      enabled: true
  datasource:
      generate-unique-name: false
      url: jdbc:h2:mem:sk-internship-db
      username: sa
      password:

# MyBatis
mybatis:
  mapper-locations: mybatis-mapper/**/*.xml # mapper.xml 위치 지정
  type-aliases-package: SKInternship.board.domain # 패키지 명을 생략할 수 있도록 alias 설정
  configuration:
    map-underscore-to-camel-case: true # model 프로퍼티 camel case 설정

